services:
  movie:
    image: movie
    build:
      context: .
      dockerfile: Movie/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=mydatabase
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
volumes:
  mysql_data:

