services:
  api:
    image: movie-api
    build:
      context: .
      dockerfile: Movie.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=mydatabase
    networks:
      - app-network
networks:
  app-network:
volumes:
  mysql_data:

